### ISSUE TITLE
#TK Establecer una versión específica de Android Studio que será utilizada de manera consistente en todo el proyecto. Esto garantizará la compatibilidad y la coherencia entre los miembros del equipo y facilitará la gestión de dependencias y actualizaciones.

### ISSUE THREAD

**Issue by NoeCoast** [Dev-Full-Solutions/AnalizAr#61]
- [x]  Investigar las versiones disponibles de Android Studio y evaluar las características y mejoras ofrecidas por cada una. 

- [x] Consultar con el equipo de desarrollo para recopilar opiniones y preferencias sobre la versión de Android Studio a utilizar. 

- [x] Analizar la compatibilidad de la versión seleccionada con las dependencias y bibliotecas del proyecto. 

- [x] Documentar la versión definitiva de Android Studio seleccionada y comunicar de manera clara y concisa a todo el equipo. 

**Criterios de aceptación:** 

- [x]  Se ha seleccionado una versión específica de Android Studio basada en la investigación y las consultas con el equipo.

- [x]  La versión seleccionada es compatible con las dependencias y bibliotecas utilizadas en el proyecto.

- [x] Se ha comunicado la versión definitiva de Android Studio de manera efectiva a todos los miembros del equipo de desarrollo.

**Comment by NoeCoast** [comment]
Debería contar con la participación activa de la totalidad de los desarrolladores:
@todotirreno @DiegolPl @ChristMorales @KaterinnePeralta @NoeCoast @NoeVelaz @danielpozzo @anibal-morales

**Comment by danielpozzo** [comment]
Después de varias pruebas de instalación y configuración de Android Studio en mi equipo concluyo que la mejor opción para continuar el desarrollo del actual proyecto es seguir utilizando la versión Giraffe.
En mi caso instalé la 2022.3.1.22 dónde 2022.3.1 es la versión Giraffe y .22 es el Patch 4 de la misma.

**Comment by danielpozzo** [comment]
Respecto del segundo item de la #TK entiendo que no sería necesario debatirlo ya que todos tienen instalada dichá versión en sus equipos y sabemos que funcionan las dependencias del proyecto móvil anteriormente desarrollado.
Por lo tanto entiendo que no hay ventajas al  implementar nuevas versiones de Android Studio.

**Comment by DiegolPl** [comment]
Comparto prácticamente la misma versión que @danielpozzo salvo que el Patch en mi caso es el 2. Hice pruebas de la aplicación emulándolo en mi smartphone y corre bien, sin ningún error, por lo cual entiendo que no presenta errores de compatibilidad con las dependencias del proyecto.

**Comment by NoeCoast** [comment]
Giraffe: 2022.3.1
Patch 1
Android Gradle Plugins Version: 8.1.2
Gradle Version; 8.0
SDK Version: API 33
Kotlin Version: 1.8.10
Groovy Version: 3.0.13
JVM: 17.0.8
Pixel:(411 x 731 dp, 420dpi)

**Comment by danielpozzo** [comment]
Con la finalidad de completar esta tarea adjunto una tabla con el versionado propuesto para el presente desarrollo y versiones más y menos actualizadas que guardan compatibilidad con las definidas.

![Image](https://github.com/Dev-Full-Solutions/AnalizAr/assets/106629005/7e9bc1ae-3458-4fb1-a6a6-deaeca0092f4)

**Comment by danielpozzo** [comment]
He documentado el versionado a utilizar y sus opcionales en Bitácora - Contribuciones Semana 1 Sprint 2 de la Wiki en en repositorio AnalizAr.
https://github.com/Dev-Full-Solutions/AnalizAr/wiki/Bit%C3%A1cora-%E2%80%90-Registro-de-Actividades-del-Equipo-de-Desarrollo#semana-1-2
